### PR TITLE
RELEASE 2.2.0

### PR DESCRIPTION
**Pull request by ndelangen**
I've added myself to the contributors list on npm and released a new version: 2.2.0

### CODE REVIEW

**Comment by gorillamania** [comment]
Please also add a tag

**Comment by gorillamania** [comment]
And thank you! @changetip 1 beer @ndelangen

**Comment by changetip** [comment]
Hi @ndelangen, @gorillamania sent you a tip worth 1 beer (4,724 bits/$3.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/948947)**.



**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by ndelangen** [comment]
I've tagged it on my end. Don't know how to make it push a tag onto your repo.

**Pull request merged**
