### PR TITLE
Add `silent` grunt option, actually define defaults, update readme syntax (linted with markdownlint)

### PR DESCRIPTION
**Pull request by davidosomething**
Add `silent` grunt option, actually define defaults, update readme syntax (linted with markdownlint)

### CODE REVIEW

**Comment by davidosomething** [comment]
N.B. does not include a readme changelog update or version bump

**Comment by davidosomething** [comment]
@gorillamania you around?

**Comment by gorillamania** [comment]
Thanks for doing the work! @changetip give this guy a coffee.

**Comment by changetip** [comment]
Hi @davidosomething, @gorillamania sent you a tip worth a coffee (6,276 bits/$1.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/896190)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Pull request merged**
