### PR TITLE
need to point at exe not cmd for windows or it will return instantly …

### PR DESCRIPTION
**Pull request by mikemellor11**
…befores tests run. Relating to issue #81

### CODE REVIEW

**Comment by TechNickAI** [comment]
@ndelangen  can you review and push a new version?

**Comment by mikemellor11** [comment]
Hi, sorry by push a new version do you mean tagging a new release?

**Comment by TechNickAI** [comment]
@mikemellor11 - I was talking to @ndelangen - who has push access to npm.

**Comment by ndelangen** [comment]
Sorry, I'm in between jobs at the moment, and I don't have a computer set up to do development on. I'll probably be able to push a new version this weekend.

**Comment by ndelangen** [comment]
2.2.1 has been released: https://www.npmjs.com/package/grunt-casperjs

**Pull request merged**
